[package]
name = "ownable_count"
version = "0.1.0"
edition = "2023_10"
cairo-version = "2.3.1"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=2.3.1"

[[targe.starknet-contract]]
sierra = true